'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { PageHeader } from '@/components/shared/PageHeader';
import { InsightCard } from '@/components/ai/InsightCard';
import { InsightStream } from '@/components/ai/InsightStream';
import { aiInsights } from '@/data/mock';
import { cn } from '@/lib/utils';
import { Sparkles, Filter, Lightbulb, AlertTriangle, TrendingUp } from 'lucide-react';

type CategoryFilter = 'all' | 'observation' | 'anomaly' | 'trend' | 'suggestion';
type PersonaFilter = 'all' | 'hr' | 'engineering' | 'product';

const categoryFilters: { key: CategoryFilter; label: string; icon: React.ElementType }[] = [
  { key: 'all', label: 'All', icon: Sparkles },
  { key: 'observation', label: 'Observations', icon: Lightbulb },
  { key: 'anomaly', label: 'Anomalies', icon: AlertTriangle },
  { key: 'trend', label: 'Trends', icon: TrendingUp },
  { key: 'suggestion', label: 'Suggestions', icon: Sparkles },
];

const personaFilters: { key: PersonaFilter; label: string }[] = [
  { key: 'all', label: 'All Perspectives' },
  { key: 'hr', label: 'People & Culture' },
  { key: 'engineering', label: 'Engineering' },
  { key: 'product', label: 'Product' },
];

export default function InsightsPage() {
  const [categoryFilter, setCategoryFilter] = useState<CategoryFilter>('all');
  const [personaFilter, setPersonaFilter] = useState<PersonaFilter>('all');

  const filteredInsights = aiInsights.filter((insight) => {
    if (categoryFilter !== 'all' && insight.category !== categoryFilter) return false;
    if (personaFilter !== 'all' && insight.persona !== personaFilter && insight.persona !== 'all') return false;
    return true;
  });

  return (
    <div className="max-w-[1400px] mx-auto">
      <PageHeader
        title="AI Insights"
        description="AI-generated observations, anomalies, and suggestions extracted from your connected data sources. All insights are probabilistic and meant to assist decision-making, not replace it."
        badge={{ label: 'AI', color: 'text-accent bg-accent-dim' }}
      />

      {/* Disclaimer */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.2 }}
        className="mb-8 p-4 rounded-lg border border-accent/10 bg-accent-dim/30"
      >
        <div className="flex items-start gap-3">
          <Sparkles className="w-4 h-4 text-accent mt-0.5 flex-shrink-0" />
          <div>
            <p className="text-xs text-text-secondary leading-relaxed">
              These insights are generated by analyzing patterns across your connected tools. Each insight includes a confidence score and data sources.
              <span className="text-accent font-medium"> They are designed to surface patterns you might miss, not to make judgments.</span>
            </p>
          </div>
        </div>
      </motion.div>

      {/* ── AI Summary ── */}
      <div className="mb-10">
        <InsightStream
          message="I've generated 7 insights this period from analyzing data across GitHub, Jira, Slack, and Email. The most actionable items are: an unusual spike in Frontend team failure rates, a potential schedule risk for Mobile App MVP, and a collaboration pattern shift for Nina Okafor that may warrant attention."
          typing
        />
      </div>

      {/* ── Filters ── */}
      <div className="flex flex-col sm:flex-row gap-4 mb-8">
        {/* Category filters */}
        <div className="flex items-center gap-1.5 p-1 rounded-lg bg-surface-1 border border-border-subtle">
          {categoryFilters.map((filter) => {
            const Icon = filter.icon;
            const isActive = categoryFilter === filter.key;

            return (
              <button
                key={filter.key}
                onClick={() => setCategoryFilter(filter.key)}
                className={cn(
                  'flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all duration-200',
                  isActive
                    ? 'bg-surface-3 text-text-primary shadow-sm'
                    : 'text-text-tertiary hover:text-text-secondary',
                )}
              >
                <Icon className="w-3 h-3" />
                {filter.label}
              </button>
            );
          })}
        </div>

        {/* Persona filters */}
        <div className="flex items-center gap-1.5 p-1 rounded-lg bg-surface-1 border border-border-subtle">
          {personaFilters.map((filter) => {
            const isActive = personaFilter === filter.key;

            return (
              <button
                key={filter.key}
                onClick={() => setPersonaFilter(filter.key)}
                className={cn(
                  'px-3 py-1.5 rounded-md text-xs font-medium transition-all duration-200',
                  isActive
                    ? 'bg-surface-3 text-text-primary shadow-sm'
                    : 'text-text-tertiary hover:text-text-secondary',
                )}
              >
                {filter.label}
              </button>
            );
          })}
        </div>
      </div>

      {/* ── Results count ── */}
      <div className="flex items-center gap-2 mb-6">
        <span className="text-xs font-mono text-text-ghost">
          {filteredInsights.length} insight{filteredInsights.length !== 1 ? 's' : ''}
        </span>
        <div className="flex-1 h-px bg-border-subtle" />
      </div>

      {/* ── Insights Grid ── */}
      <AnimatePresence mode="wait">
        <motion.div
          key={`${categoryFilter}-${personaFilter}`}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="grid grid-cols-1 md:grid-cols-2 gap-4"
        >
          {filteredInsights.map((insight, i) => (
            <InsightCard key={insight.id} insight={insight} delay={i} />
          ))}
        </motion.div>
      </AnimatePresence>

      {filteredInsights.length === 0 && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-center py-16"
        >
          <div className="w-12 h-12 rounded-xl bg-surface-2 flex items-center justify-center mx-auto mb-4">
            <Filter className="w-5 h-5 text-text-ghost" />
          </div>
          <p className="text-sm text-text-tertiary">No insights match the current filters</p>
          <button
            onClick={() => { setCategoryFilter('all'); setPersonaFilter('all'); }}
            className="text-xs text-accent hover:text-accent/80 mt-2 transition-colors"
          >
            Clear filters
          </button>
        </motion.div>
      )}
    </div>
  );
}
